//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullaniciBilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kullaniciBilgi()
        {
            this.kullaniciLogin = new HashSet<kullaniciLogin>();
            this.Takip = new HashSet<Takip>();
            this.Takip1 = new HashSet<Takip>();
        }
    
        public int kullaniciId { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public string mail { get; set; }
        public int telefon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullaniciLogin> kullaniciLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Takip> Takip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Takip> Takip1 { get; set; }
    }
}
