//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class instEntities1 : DbContext
    {
        public instEntities1()
            : base("name=instEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Begeni> Begeni { get; set; }
        public virtual DbSet<Gonderi> Gonderi { get; set; }
        public virtual DbSet<kullaniciBilgi> kullaniciBilgi { get; set; }
        public virtual DbSet<kullaniciLogin> kullaniciLogin { get; set; }
        public virtual DbSet<Takip> Takip { get; set; }
        public virtual DbSet<Yorum> Yorum { get; set; }
    }
}
