//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Takip
    {
        public int Id { get; set; }
        public int TakipEden { get; set; }
        public int TakipEdilen { get; set; }
    
        public virtual kullaniciBilgi kullaniciBilgi { get; set; }
        public virtual kullaniciBilgi kullaniciBilgi1 { get; set; }
    }
}
