//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int yorumId { get; set; }
        public int gonderiId { get; set; }
        public int yorumYapanId { get; set; }
        public System.DateTime tarih { get; set; }
        public string yorum1 { get; set; }
    
        public virtual Gonderi Gonderi { get; set; }
        public virtual kullaniciLogin kullaniciLogin { get; set; }
    }
}
